source_db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: ""
  dbname: "postgres"

destination_db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: ""
  dbname: "postgres2"

tables:
  - name: "tbl1"
    mask_columns:
      - "email"
