CREATE TABLE TRANSACTIONS (
    ID VARCHAR(36) PRIMARY KEY,
    CLIENT_ID VARCHAR(36)
);

CREATE TABLE CLIENTS (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(255),
    SURNAME VARCHAR(255),
    MIDDLE_NAME VARCHAR(255),
    BIRTH_DATE DATE,
    DELETED BOOLEAN DEFAULT FALSE
);

INSERT INTO CLIENTS (ID, NAME, SURNAME, MIDDLE_NAME, BIRTH_DATE, DELETED) VALUES ('1', 'John', '', 'Smith', '1990-01-01', FALSE);
INSERT INTO CLIENTS (ID, NAME, SURNAME, MIDDLE_NAME, BIRTH_DATE, DELETED) VALUES ('2', 'Jane', 'Mary', 'Smith', '1991-02-03', FALSE);